---
sudo: false
dist: xenial
language: python
cache: pip

services:
  - postgresql

matrix:
  include:
    # https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django
    - {env: DJANGO=1.11, python: '2.7'}
    - {env: DJANGO=1.11, python: '3.5'}
    - {env: DJANGO=1.11, python: '3.6'}
    - {env: DJANGO=1.11, python: '3.7'}
    - {env: DJANGO=1.11, python: '3.8'}
    - {env: DJANGO=1.11, python: 'pypy2.7-6.0'}
    - {env: DJANGO=1.11, python: 'pypy3.5-6.0'}

    - {env: DJANGO=2.2, python: '3.5'}
    - {env: DJANGO=2.2, python: '3.6'}
    - {env: DJANGO=2.2, python: '3.7'}
    - {env: DJANGO=2.2, python: '3.8'}
    - {env: DJANGO=2.2, python: 'nightly'}
    - {env: DJANGO=2.2, python: 'pypy3.5-6.0'}

    - {env: DJANGO=master, python: '3.6'}
    - {env: DJANGO=master, python: '3.7'}
    - {env: DJANGO=master, python: '3.7'}
    - {env: DJANGO=master, python: 'nightly'}

  allow_failures:
    - python: 'nightly'
    - env: DJANGO=master

install:
    - if [[ $DJANGO == 'master' ]]; then travis_retry pip install https://github.com/django/django/archive/master.tar.gz; fi
    - if [[ $DJANGO != 'master' ]]; then travis_retry pip install django==$DJANGO; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy'* ]]; then travis_retry pip install psycopg2cffi>=2.7; fi
    - if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then travis_retry pip install psycopg2-binary; fi
    - travis_retry pip install gevent
    - python setup.py -q install

before_script:
  - psql -c 'create database test;' -U postgres

script:
  - python -Wall runtests.py
